server:
  port: 8081

spring:
  application:
    name: SERVICE-PROVIDER111
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://127.0.0.1:3306/1812?useUnicode=true&characterEncoding=utf-8
    username: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
mybatis:
  mapper-locations: classpath:mapper/*.xml




